### PR TITLE
update and clean up demo section

### PR DESCRIPTION
**Pull request by groovecoder**

### CODE REVIEW

**Comment by groovecoder** [comment]
Hmm ... http://www.wellhub.co/ now has 50x error. :( I don't think anything in this commit would have broken it. We may just need to figure out how to re-build the gh-pages? Might be as easy as pushing a blank (or nearly blank) commit to the branch?

**Comment by Yahyaal** [comment]
huh.. i tested it right after merging the commit and it opened fine. not
sure what happened

**Comment by Yahyaal** [comment]
i just clicked on the "http://yahyaal.github.io/WellHub2/" link and it seems working fine. i guess the problem is with the .co domaine

**Comment by groovecoder** [comment]
Ah, yeah must be on .co side. Which registrar did we use?

**Comment by Yahyaal** [comment]
pop.co, i have forwarded to you their email that has the username and password for the account

**Pull request merged**
